[book]
title = "Guide for https://gitlab.com/jimcooke/markdown-book"
description = "Guide on using the markdown-book repository to quickly set up your markdown documentation repository"
authors = ["Jim Cooke"]
language = "en"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2